# Generated by Django 3.1.5 on 2021-04-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0018_usuario_ris'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionAnexo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(choices=[(2021, '2021'), (2020, '2020')], verbose_name='Año')),
                ('periodo', models.PositiveIntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], verbose_name='Periodo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='setup.usuario')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.entidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to='setup.usuario')),
            ],
            options={
                'verbose_name': 'Evaluación Anexo 1',
                'verbose_name_plural': 'Evaluaciones Anexo 1',
                
            },
        ),
        migrations.CreateModel(
            name='DetalleEvaluacionAnexo1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.BooleanField(default=False, verbose_name='Calificación')),
                ('observacion', models.TextField(blank=True, max_length=700, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_created_by', to='setup.usuario')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reclamo_administrador.evaluacionanexo1')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.rubrocalificacion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_updated_by', to='setup.usuario')),
            ],
            options={
                'verbose_name': 'Detalle evaluación Anexo 1',
                'verbose_name_plural': 'Detalles Evaluacion Anexo 1',
                'ordering': ['evaluacion', 'rubro__orden'],
            },
        ),
    ]
