# Generated by Django 3.1.5 on 2021-04-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_usuario_ris'),
        ('reclamo_administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluacionanexo1',
            unique_together={('entidad', 'anio', 'periodo')},
        ),
    ]
