# Generated by Django 3.1.5 on 2021-04-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo_administrador', '0003_auto_20210416_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionanexo1',
            name='periodo',
            field=models.PositiveIntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], verbose_name='Periodo'),
        ),
    ]
