# Generated by Django 3.1.5 on 2022-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo_administrador', '0004_auto_20210416_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionanexo1',
            name='anio',
            field=models.PositiveIntegerField(choices=[(2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Año'),
        ),
    ]
