# Generated by Django 5.0.7 on 2024-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo_administrador', '0005_auto_20220208_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionanexo1',
            name='anio',
            field=models.PositiveIntegerField(choices=[(2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Año'),
        ),
    ]
