# Generated by Django 5.1.1 on 2024-11-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo_administrador', '0006_alter_evaluacionanexo1_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionanexo1',
            name='anio',
            field=models.PositiveIntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Año'),
        ),
    ]
