# Generated by Django 3.1.5 on 2021-02-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('icon', models.CharField(default='home', max_length=30, verbose_name='icono')),
                ('url', models.CharField(max_length=30, verbose_name='url')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='título')),
                ('type', models.IntegerField(choices=[(0, 'PERFIL_PACIENTE'), (1, 'ADMINISTRADOR')], default=1, verbose_name='tipo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='setup.menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='GroupMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('menus', models.ManyToManyField(blank=True, help_text='Especifica los menus del grupo.', to='setup.Menu', verbose_name='grupos menus')),
            ],
            options={
                'verbose_name': 'Grupo Menu',
                'verbose_name_plural': 'Grupo Menus',
            },
        ),
    ]
