# Generated by Django 3.1.5 on 2021-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_entidad_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='renipress',
        ),
        migrations.AddField(
            model_name='entidad',
            name='categoria',
            field=models.PositiveIntegerField(choices=[(1, 'I-1'), (2, 'I-2'), (3, 'I-3'), (4, 'I-4')], default=1, verbose_name='Categoría'),
        ),
    ]
