# Generated by Django 3.1.5 on 2021-02-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20210210_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='ris',
            field=models.PositiveIntegerField(choices=[(1, 'RIS BCO-CHO-SCO'), (2, 'RIS LURIN Y BALNERARIOS'), (3, 'RIS PACHACAMAC'), (4, 'RIS SJM'), (5, 'RIS VES'), (6, 'RIS VMT')], default=1, verbose_name='RIS'),
        ),
    ]
