# Generated by Django 3.1.5 on 2021-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_entidad_ris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='document',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='número de DNI'),
        ),
    ]
