# Generated by Django 3.1.5 on 2021-02-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20210210_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.entidad'),
            preserve_default=False,
        ),
    ]
