# Generated by Django 3.1.5 on 2021-02-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20210210_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=80, unique=True, verbose_name='periodo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de incio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('estado', models.BooleanField(blank=True, max_length=30, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
    ]
