# Generated by Django 3.1.5 on 2021-02-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubroCalificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(unique=True, verbose_name='Orden')),
                ('rubro', models.TextField(max_length=600, verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Rubros calificación',
                'verbose_name_plural': 'Rubros calificación',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='periodo',
            name='estado',
            field=models.BooleanField(default=True, max_length=30, verbose_name='Estado'),
        ),
    ]
