# Generated by Django 3.1.5 on 2021-02-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20210211_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'IPRESS'), (2, 'UGIPRESS'), (3, 'IAFAS')], default=1, verbose_name='Tipo'),
        ),
    ]
