# Generated by Django 3.1.5 on 2021-03-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_entidad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.entidad'),
        ),
    ]
