# Generated by Django 3.1.5 on 2021-03-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_auto_20210304_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='nombre'),
        ),
    ]
