# Generated by Django 3.1.5 on 2021-03-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_auto_20210304_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
    ]
