# Generated by Django 3.1.5 on 2021-03-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_auto_20210304_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='ris',
            field=models.PositiveIntegerField(choices=[(1, 'RIS BCO-CHO-SCO'), (2, 'RIS LURIN Y BALNERARIOS'), (3, 'RIS PACHACAMAC'), (4, 'RIS SJM'), (5, 'RIS VES'), (6, 'RIS VMT'), (7, 'DIRIS SEDE ADMINISTRATIVA')], default=1, verbose_name='RIS'),
        ),
    ]
