# Generated by Django 3.1.5 on 2021-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_auto_20210318_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(max_length=80, verbose_name='url'),
        ),
    ]
