# Generated by Django 3.1.5 on 2021-04-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_auto_20210329_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='tipo',
        ),
    ]
