# Generated by Django 3.1.5 on 2021-04-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_remove_entidad_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ris',
            field=models.IntegerField(choices=[(0, ' ----------'), (1, 'RIS BCO-CHO-SCO'), (2, 'RIS LURIN Y BALNERARIOS'), (3, 'RIS PACHACAMAC'), (4, 'RIS SJM'), (5, 'RIS VES'), (6, 'RIS VMT'), (7, 'DIRIS SEDE ADMINISTRATIVA')], default=0, verbose_name='Administrador RIS'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.entidad', verbose_name='IPRESS'),
        ),
    ]
