# Generated by Django 3.1.5 on 2021-04-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_auto_20210413_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ris',
        ),
    ]
