# Generated by Django 3.1.5 on 2021-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_remove_usuario_ris'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ris',
            field=models.IntegerField(choices=[(0, ' ----------'), (1, 'RIS BCO-CHO-SCO'), (2, 'RIS LURIN Y BALNERARIOS'), (3, 'RIS PACHACAMAC'), (4, 'RIS SJM'), (5, 'RIS VES'), (6, 'RIS VMT'), (7, 'DIRIS SEDE ADMINISTRATIVA')], default=0, verbose_name='Administrador RIS'),
        ),
    ]
