# Generated by Django 3.1.5 on 2022-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_usuario_ris'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='numero_medidas_adoptados',
            field=models.IntegerField(default=0, verbose_name='Número de medidas adoptadas'),
        ),
        migrations.AddField(
            model_name='entidad',
            name='numero_reclamos',
            field=models.IntegerField(default=0, verbose_name='Número de reclamos'),
        ),
    ]
