# Generated by Django 3.1.5 on 2022-03-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20220208_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='codigo',
            field=models.CharField(max_length=150, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='nombre'),
        ),
    ]
