from django.http import HttpResponse
from django.template import loader

from apps.reclamo.models.entidad_reclamo import MESES
from apps.reclamo.models.medida_adoptada import MedidaAdoptada
from apps.util.anios import ANIOS
from apps.util.update_menu import update_menu


def reporte_trama_medidas_adoptadas(request):
    update_menu(request)
    template = loader.get_template('trama_txt/medidas_adoptadas.html')

    context = {
        'title': 'GENERAR TRAMA DE MEDIDAS ADOPTADAS',
        'anios': ANIOS,
        'meses': MESES
    }

    if request.method == 'GET':
        context['s'] = 'sd'
    elif request.method == 'POST':
        anio = request.POST.get('anio', '2020')
        mes = request.POST.get('mes', '1')
        context['anio'] = int(anio)
        context['mes'] = int(mes)

        # msg = "Reporte generado del año: " + str(anio)
        # messages.add_message(request, messages.SUCCESS, msg)

        filename = "10000122_" + request.session['entidad_codigo'].zfill(8) + "_" + anio + "_" + mes.zfill(
            2) + "_MEDIDAS.TXT"
        # content = 'any string generated by django'

        medidas_adoptadas_list = MedidaAdoptada.objects.filter(fecha_inicio__year=anio,
                                                               fecha_inicio__month=mes,
                                                               entidad_reclamo__entidad_id=request.session['entidad_id'])

        content = ''

        for r in medidas_adoptadas_list:
            # ENTIDAD QUE REPORTA EL RECLAMO A LA SUPRERINTENDENCIA
            c1 = str(r.entidad_reclamo.medio_presentacion)
            c2 = r.entidad_reclamo.codigo_registro.strip()
            c3 = r.codigo.strip()
            c4 = r.descripcion.strip()
            c5 = str(r.naturaleza)
            c6 = str(r.procesos)
            c7 = r.fecha_inicio.strftime('%Y%m%d')
            c8 = r.fecha_culminacion.strftime('%Y%m%d')

            content += c1 + '|' + c2 + '|' + c3 + '|' + c4 + '|' + c5 + '|' + c6 + '|' + c7 + '|' + c8 + '\n'

        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response

    return HttpResponse(template.render(context, request))
