from django.http import HttpResponse
from django.template import loader

from apps.reclamo.models.entidad_reclamo import MESES, EntidadReclamo
from apps.util.anios import ANIOS
from apps.util.update_menu import update_menu


def reporte_trama_reclamos(request):
    update_menu(request)
    template = loader.get_template('trama_txt/reclamos.html')

    context = {
        'title': 'GENERAR TRAMA DE RECLAMOS',
        'anios': ANIOS,
        'meses': MESES
    }

    if request.method == 'GET':
        context['s'] = 'sd'
    elif request.method == 'POST':
        anio = request.POST.get('anio', '2020')
        mes = request.POST.get('mes', '1')
        context['anio'] = int(anio)
        context['mes'] = int(mes)

        # msg = "Reporte generado del año: " + str(anio)
        # messages.add_message(request, messages.SUCCESS, msg)

        filename = "10000122_" + request.session['entidad_codigo'] + "_" + anio + "_" + mes.zfill(
            2) + "_RECLAMOS.TXT"
        # content = 'any string generated by django'

        reclamo_list = EntidadReclamo.objects.filter(fecha_reclamo__year=anio,
                                                     fecha_reclamo__month=mes, entidad_id=request.session['entidad_id'])
        content = ''

        for r in reclamo_list:
            # ENTIDAD QUE REPORTA EL RECLAMO A LA SUPRERINTENDENCIA
            c1 = r.periodo
            c2 = '1'
            c3 = r.entidad.codigo.strip()
            c4 = '10000122'
            c5 = str(r.tipo_institucion)
            c6 = r.codigo_administrado
            c7 = str(r.medio_presentacion)
            c8 = r.codigo_registro.strip()

            # IDENTIFICACION DEL USUARIO O TERCERO LEGITIMADO
            c9 = str(r.tipo_documento_usuario)
            c10 = r.numero_documento_usuario.strip() if r.numero_documento_usuario else ''
            c11 = r.razon_social_usuario.strip() if r.razon_social_usuario else ''
            c12 = r.nombres_usuario.strip() if r.nombres_usuario else ''
            c13 = r.apellido_paterno_usuario.strip() if r.apellido_paterno_usuario else ''
            c14 = r.apellido_materno_usuario.strip() if r.apellido_materno_usuario else ''

            # IDENTIFICACION DEL QUIEN PRESENTA EL RECLAMO
            c15 = str(r.tipo_documento_presenta)
            c16 = r.numero_documento_presenta.strip() if r.numero_documento_presenta else ''
            c17 = r.razon_social_presenta.strip() if r.razon_social_presenta else ''
            c18 = r.nombres_presenta.strip() if r.nombres_presenta else ''
            c19 = r.apellido_paterno_presenta.strip() if r.apellido_paterno_presenta else ''
            c20 = r.apellido_materno_presenta.strip() if r.apellido_materno_presenta else ''

            c21 = str(r.autorizacion_notificacion_correo)
            c22 = str(r.correo_presenta).strip() if r.correo_presenta else ''
            c23 = str(r.domicilio_presenta).strip() if r.domicilio_presenta else ''
            c24 = str(r.celular_presenta).strip() if r.celular_presenta else ''

            # DETALLE DEL RECLAMO

            c25 = str(r.medio_recepcion_reclamo)
            c26 = r.fecha_reclamo.strftime('%Y%m%d')
            c27 = r.detalle_reclamo.strip() if r.detalle_reclamo else ''

            # DE LA GESTIÓN DEL RECLAMO

            c28 = r.servicio_hecho_reclamo
            c29 = str(r.competencia_reclamo)
            c30 = str(r.clasificacion_reclamo_1.codigo) if r.clasificacion_reclamo_1 else ''
            c31 = str(r.clasificacion_reclamo_2.codigo) if r.clasificacion_reclamo_2 else ''
            c32 = str(r.clasificacion_reclamo_3.codigo) if r.clasificacion_reclamo_3 else ''
            c33 = str(r.estado_reclamo)
            c34 = r.codigo_reclamo_primigenio.strip() if r.codigo_reclamo_primigenio else ''
            c35 = str(r.etapa_reclamo)
            c36 = str(r.tipo_administrado_traslado) if r.tipo_administrado_traslado else ''
            c37 = r.codigo_administrado_deriva.strip().zfill(8) if r.codigo_administrado_deriva else ''

            # RESULTADO DEL RECLAMO

            c38 = str(r.resultado_reclamo) if r.resultado_reclamo else ''
            c39 = str(r.motivo_conclusion_anticipada) if r.motivo_conclusion_anticipada else ''
            c40 = r.fecha_resultado_reclamo.strftime('%Y%m%d') if r.fecha_resultado_reclamo else ''
            c41 = str(r.comunicacion_resultado_reclamo) if r.comunicacion_resultado_reclamo else ''
            c42 = r.fecha_notificacion.strftime('%Y%m%d') if r.fecha_notificacion else ''

            content += c1 + '|' + c2 + '|' + c3 + '|' + c4 + '|' + c5 + '|' + c6 + '|' + c7 + '|' + c8 + \
                       '|' + c9 + '|' + c10 + '|' + c11 + '|' + c12 + '|' + c13 + '|' + c14 + \
                       '|' + c15 + '|' + c16 + '|' + c17 + '|' + c18 + '|' + c19 + '|' + c20 + \
                       '|' + c21 + '|' + c22 + '|' + c23 + '|' + c24 + \
                       '|' + c25 + '|' + c26 + '|' + c27 + '|' + \
                       c28 + '|' + c29 + '|' + c30 + '|' + c31 + '|' + c32 + '|' + c33 + '|' + c34 + '|' + c35 + '|' + c36 + '|' + c37 + \
                       '|' + c38 + '|' + c39 + '|' + c40 + '|' + c41 + '|' + c42 + '\n'

        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response

    return HttpResponse(template.render(context, request))
