from django.http import HttpResponse
from django.template import loader

from apps.reclamo.models.entidad_reclamo import MESES, EntidadReclamo
from apps.util.anios import ANIOS
from apps.util.update_menu import update_menu

def safe_str(value):
    return str(value) if value is not None else ''
def reporte_trama_reclamos_diris(request):
    update_menu(request)
    template = loader.get_template('trama_txt/reclamos_diris.html')

    context = {
        'title': 'GENERAR TRAMA DE RECLAMOS',
        'anios': ANIOS,
        'meses': MESES
    }

    if request.method == 'GET':
        context['s'] = 'sd'
    elif request.method == 'POST':
        anio = request.POST.get('anio', '2020')
        mes = request.POST.get('mes', '1')
        context['anio'] = int(anio)
        context['mes'] = int(mes)

        # msg = "Reporte generado del año: " + str(anio)
        # messages.add_message(request, messages.SUCCESS, msg)

        filename = "10000122_"   + "_" + anio + "_" + mes.zfill(
            2) + "_RECLAMOS.TXT"
        # content = 'any string generated by django'

        reclamo_list = EntidadReclamo.objects.filter(fecha_reclamo__year=anio,
                                                     fecha_reclamo__month=mes)
        content = ''

        for r in reclamo_list:
            # ENTIDAD QUE REPORTA EL RECLAMO A LA SUPRERINTENDENCIA
            c1 = r.periodo
            c2 = '1'
            c3 = safe_str(r.entidad.codigo).strip()
            c4 = '10000122'
            c5 = safe_str(r.tipo_institucion)
            c6 = safe_str(r.codigo_administrado)
            c7 = safe_str(r.medio_presentacion)
            c8 = safe_str(r.codigo_registro).strip()

            # IDENTIFICACION DEL USUARIO O TERCERO LEGITIMADO
            c9 = safe_str(r.tipo_documento_usuario)
            c10 = safe_str(r.numero_documento_usuario).strip()
            c11 = safe_str(r.razon_social_usuario).strip()
            c12 = safe_str(r.nombres_usuario).strip()
            c13 = safe_str(r.apellido_paterno_usuario).strip()
            c14 = safe_str(r.apellido_materno_usuario).strip()

             # IDENTIFICACION DEL QUIEN PRESENTA EL RECLAMO
            c15 = safe_str(r.tipo_documento_presenta)
            c16 = safe_str(r.numero_documento_presenta).strip()
            c17 = safe_str(r.razon_social_presenta).strip()
            c18 = safe_str(r.nombres_presenta).strip()
            c19 = safe_str(r.apellido_paterno_presenta).strip()
            c20 = safe_str(r.apellido_materno_presenta).strip()

            c21 = safe_str(r.autorizacion_notificacion_correo)
            c22 = safe_str(r.correo_presenta).strip()
            c23 = safe_str(r.domicilio_presenta).strip()
            c24 = safe_str(r.celular_presenta).strip()

                # DETALLE DEL RECLAMO
            c25 = safe_str(r.medio_recepcion_reclamo)
            c26 = r.fecha_reclamo.strftime('%Y%m%d')
            c27 = safe_str(r.detalle_reclamo).strip()

                # DE LA GESTIÓN DEL RECLAMO
            c28 = safe_str(r.servicio_hecho_reclamo)
            c29 = safe_str(r.competencia_reclamo)
            c30 = safe_str(r.clasificacion_reclamo_1.codigo) if r.clasificacion_reclamo_1 else ''
            c31 = safe_str(r.clasificacion_reclamo_2.codigo) if r.clasificacion_reclamo_2 else ''
            c32 = safe_str(r.clasificacion_reclamo_3.codigo) if r.clasificacion_reclamo_3 else ''
            c33 = safe_str(r.estado_reclamo)
            c34 = safe_str(r.codigo_reclamo_primigenio).strip()
            c35 = safe_str(r.etapa_reclamo)
            c36 = safe_str(r.tipo_administrado_traslado)
            c37 = safe_str(r.codigo_administrado_deriva).strip()

                # RESULTADO DEL RECLAMO
            c38 = safe_str(r.resultado_reclamo)
            c39 = safe_str(r.motivo_conclusion_anticipada)
            c40 = r.fecha_resultado_reclamo.strftime('%Y%m%d') if r.fecha_resultado_reclamo else ''
            c41 = safe_str(r.comunicacion_resultado_reclamo)
            c42 = r.fecha_notificacion.strftime('%Y%m%d') if r.fecha_notificacion else ''
            content += c1 + '|' + c2 + '|' + c3 + '|' + c4 + '|' + c5 + '|' + c6 + '|' + c7 + '|' + c8 + \
                       '|' + c9 + '|' + c10 + '|' + c11 + '|' + c12 + '|' + c13 + '|' + c14 + \
                       '|' + c15 + '|' + c16 + '|' + c17 + '|' + c18 + '|' + c19 + '|' + c20 + \
                       '|' + c21 + '|' + c22 + '|' + c23 + '|' + c24 + \
                       '|' + c25 + '|' + c26 + '|' + c27 + '|' + \
                       c28 + '|' + c29 + '|' + c30 + '|' + c31 + '|' + c32 + '|' + c33 + '|' + c34 + '|' + c35 + '|' + c36 + '|' + c37 + \
                       '|' + c38 + '|' + c39 + '|' + c40 + '|' + c41 + '|' + c42 + '\n'

        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response

    return HttpResponse(template.render(context, request))
