# Generated by Django 3.1.5 on 2021-02-05 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadReclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_declaracion', models.CharField(blank=True, max_length=6, null=True, verbose_name='Período de declaración')),
                ('tipo_administrador', models.PositiveIntegerField(choices=[(1, 'IPRESS'), (2, 'UGIPRESS'), (3, 'IAFAS')], verbose_name='Tipo de administrado declarante')),
                ('codigo_administrador', models.CharField(blank=True, max_length=8, null=True, verbose_name='Código del administrado declarante')),
                ('codigo_ugipress', models.CharField(blank=True, max_length=8, null=True, verbose_name='Código de la UGIPRESS regístrado en SUSALUD')),
                ('tipo_institucion', models.PositiveIntegerField(choices=[(1, 'IPRESS'), (2, 'UGIPRESS'), (3, 'IAFAS')], verbose_name='Tipo de institución donde se presentó el reclamo')),
                ('codigo_administrado', models.CharField(blank=True, max_length=8, null=True, verbose_name='Código del administrador donde se presentó el reclamo')),
                ('medio_presentacion', models.PositiveIntegerField(choices=[(1, 'VIRTUAL'), (2, 'FÍSICO')], verbose_name='Medio presentación del reclamo')),
                ('codigo_registro', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Único de Registro del Reclamo asignado por el administrador')),
                ('tipo_documento_usuario', models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'CARNÉ DE EXTRANJERÍA'), (3, 'PASAPORTE'), (4, 'DOCUMENTO DE IDENTIDAD EXTRANJERO'), (5, 'CÓDIGO ÚNICO DE IDENTIFICACIÓN (CUI)'), (6, 'CERTIFICADO DE NACIDO VIVO'), (7, 'PERMISO TEMPORAL DE PERMANENCIA'), (8, 'RUC'), (9, 'OTROS')], verbose_name='Tipo de administrado declarante')),
                ('numero_documento_usuario', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número del documento de identidad del usuario afectado')),
                ('razon_social_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('nombres_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('apellido_paterno_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno_usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Materno')),
                ('tipo_documento_presenta', models.PositiveIntegerField(choices=[(1, 'DNI'), (2, 'CARNÉ DE EXTRANJERÍA'), (3, 'PASAPORTE'), (4, 'DOCUMENTO DE IDENTIDAD EXTRANJERO'), (5, 'CÓDIGO ÚNICO DE IDENTIFICACIÓN (CUI)'), (6, 'CERTIFICADO DE NACIDO VIVO'), (7, 'PERMISO TEMPORAL DE PERMANENCIA'), (8, 'RUC'), (9, 'OTROS')], verbose_name='Tipo de administrado declarante')),
                ('numero_documento_presenta', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número del documento de identidad del usuario afectado')),
                ('razon_social_presenta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('nombres_presenta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombres')),
                ('apellido_paterno_presenta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Paterno')),
                ('apellido_materno_presente', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Materno')),
                ('autorizacion_notificacion_correo', models.IntegerField(choices=[(0, 'SI'), (1, 'NO')], verbose_name='Autorización de notificación del resultado al correo electrónico')),
                ('correo_presenta', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo electrónico')),
                ('domicilio_presenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio')),
                ('celular_presenta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono fijo o Celular')),
                ('medio_recepcion_reclamo', models.PositiveIntegerField(choices=[(1, 'LIBRO DE RECLAMACIONES VIRTUAL'), (2, 'LIBRO DE RECLAMACIONES FÍSICO'), (3, 'LLAMADA TELEFÓNICA'), (4, 'RECLAMO PRESENCIAL'), (5, 'DOCUMENTO ESCRITO'), (6, 'RECLAMO TRASLADO DE OTRA ADMINISTRADA'), (7, 'RECLAMO COPARTICIPADO CON OTRA ADMINISTRADA')], verbose_name='Medio de recepción del reclamo')),
                ('fecha_reclamo', models.DateField(blank=True, null=True, verbose_name='Fecha de presentación de Reclamo')),
                ('detalle_reclamo', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Detalle del reclamo')),
                ('servicio_hecho_reclamo', models.PositiveIntegerField(choices=[(1, 'CONSULTA EXTERNA'), (2, 'HOSPITALIZACION'), (3, 'EMERGENCIA'), (4, 'CENTRO QUIRDRGICO'), (5, 'CENTRO OBSTÉTRICO'), (6, 'UCI O UCIN'), (7, 'FARMACIA'), (8, 'SERVICIOS MÉDICOS DE APOYO'), (9, 'ATENCIÉN A DOMICILIO CONSULTA AMBULATORIA'), (10, 'ATENCIÉN A DOMICILIO URGENCIA A EMERGENCIA'), (11, 'OFICINAS O AREAS ADMINISTRATIVAS DE IAFAS A 1 PRESS A UGIPRESS '), (12, 'LNFRAESTRUCTURA'), (13, 'REFERENCIA Y CONTRAREFERENCIA')], verbose_name='Servicio donde se efectuo el hecho que origino el reclamo')),
                ('competencia_reclamo', models.PositiveIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'COMPARTIDA')], verbose_name='Competencia para la atencion del reclamo')),
                ('clasificacion_reclamo_1', models.CharField(blank=True, max_length=4, null=True, verbose_name='Clasificación del reclamo 1')),
                ('clasificacion_reclamo_2', models.CharField(blank=True, max_length=4, null=True, verbose_name='Clasificación del reclamo 2')),
                ('clasificacion_reclamo_3', models.CharField(blank=True, max_length=4, null=True, verbose_name='Clasificación del reclamo 3')),
                ('estado_reclamo', models.PositiveIntegerField(choices=[(1, 'RESUELTO'), (2, 'EN TRAMITE'), (3, 'TRASLADADO'), (4, 'ARCHIVADO POR DUPLICIDAD'), (5, 'ACUMULADO'), (6, 'CONCLUIDO (CUANDO EL RESULTADO ES COMUNICADO AL RECLAMANTE O TERCERO LEGITIMADO')], verbose_name='Estado del reclamo')),
                ('codigo_reclamo_primigenio', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código de Reclamo Primigenio')),
                ('etapa_reclamo', models.PositiveIntegerField(choices=[(1, 'ADMISIÓN Y REGISTRO'), (2, 'EVALUACIÓN E INVESTIGACIÓN'), (3, 'RESULTADO Y NOTIFICACIÓN'), (4, 'ARCHIVO Y CUSTODIA DEL EXPEDIENTE')], verbose_name='Etapa del reclamo')),
                ('tipo_administrado_traslado', models.PositiveIntegerField(choices=[(1, 'IPRESS'), (2, 'UGIPRESS'), (3, 'IAFAS')], verbose_name='Tipo de Administrado a la que se deriva o  traslada el reclamo')),
                ('codigo_administrado_deriva', models.CharField(blank=True, max_length=8, null=True, verbose_name='Código del administrado a la que se deriva o traslada el reclamo')),
                ('resultado_reclamo', models.PositiveIntegerField(choices=[(1, 'FUNDADO'), (2, 'FUNDADO PARCIAL'), (3, 'INFUNDADO'), (4, 'IMPROCEDENTE'), (5, 'CONCLUIDO ANTICIPADAMENTE')], verbose_name='Resultado del Reclamo')),
                ('motivo_conclusion_anticipada', models.PositiveIntegerField(choices=[(1, 'DESISTIMIENTO POR ESCRITO'), (2, 'TRATO DIRECTO'), (3, 'CONCILIACIÓN'), (4, 'TRANSACCIÓN EXTRAJUDICIAL'), (5, 'LAUDO ARBITRAL')], verbose_name='Motivo de Conclusión anticipada')),
                ('fecha_resultado_reclamo', models.DateField(blank=True, null=True, verbose_name='Fecha de resultado del reclamo')),
                ('comunicacion_resultado_reclamo', models.PositiveIntegerField(choices=[(1, 'DOMICILIO CONSIGNADO EN EL LIBRO DE RECLAMACIONES EN SALUD'), (2, 'CORREO ELECTRÓNICO'), (3, 'OTRA DIRECCIÓN')], verbose_name='Comunicación de resultado del reclamo')),
                ('fecha_notificacion', models.DateField(blank=True, null=True, verbose_name='Fecha de notificación del resultado al usuario o tercero legitimado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_ip', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Entidad Reclamo',
                'verbose_name_plural': 'Entidades Reclamo',
            },
        ),
        migrations.CreateModel(
            name='MedidaAdoptada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código de medida adoptada o por adoptar')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Breve Descripción de la medida adoptada o por adoptar')),
                ('naturaleza', models.PositiveIntegerField(choices=[(1, 'ADMINISTRATIVA RESPECTO A PROCESOS PROPIOS DE LA IAFAS'), (2, 'ADMINISTRATIVA RESPECTO A PROCESOS PROPIOS DE LA IPRESS'), (3, 'ADMINISTRATIVA RESPECTO A PROCESOS PROPIOS DE LA UGIPRESS'), (4, 'ASISTENCIA (PRESTACIONAL)'), (5, 'ADMINISTRATIVA Y ASISTENCIAL')], verbose_name='Naturaleza de la Medida adoptada')),
                ('procesos', models.PositiveIntegerField(choices=[(1, 'AFILIACIÓN'), (2, 'ACREDITACIÓN'), (3, 'PRESTACIÓN DE SERVICIOS SALUD'), (4, 'LIQUIDACIÓN, COBRO O PAGO A USUARIO POR LOS SERVICIOS'), (5, 'CONTRALLACIÓN DE SERVICIOS DE SALUD DE UNA IAFAS A UNA IPRESS PARA ATENCIÓN DE SUS ASEGURADOS'), (6, 'OTRO PROCESO')], verbose_name='Proceso sobre el cual recae la Medida adoptada')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de implementación')),
                ('fecha_culminacion', models.DateField(blank=True, null=True, verbose_name='Fecha de culminación provista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamo.entidadreclamo')),
            ],
            options={
                'verbose_name': 'Entidad Reclamo',
                'verbose_name_plural': 'Entidades Reclamo',
            },
        ),
    ]
