# Generated by Django 3.1.5 on 2021-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionCausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True, verbose_name='Código')),
                ('derecho', models.CharField(max_length=4, unique=True, verbose_name='Derecho')),
                ('causa', models.TextField(max_length=4, unique=True, verbose_name='Causa')),
                ('definicion', models.TextField(max_length=4, unique=True, verbose_name='Definición')),
                ('definicion_corta', models.TextField(max_length=4, unique=True, verbose_name='Definición corta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clasificación de causas',
                'verbose_name_plural': 'Clasificaciones de causas',
            },
        ),
    ]
