# Generated by Django 3.1.5 on 2021-02-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0002_clasificacioncausa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadreclamo',
            options={'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
        migrations.AlterModelOptions(
            name='medidaadoptada',
            options={'verbose_name': 'Medida adoptada', 'verbose_name_plural': 'Medidas adoptadas'},
        ),
        migrations.AlterField(
            model_name='clasificacioncausa',
            name='causa',
            field=models.TextField(max_length=150, verbose_name='Causa'),
        ),
        migrations.AlterField(
            model_name='clasificacioncausa',
            name='definicion',
            field=models.TextField(max_length=1000, verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='clasificacioncausa',
            name='definicion_corta',
            field=models.TextField(max_length=500, verbose_name='Definición corta'),
        ),
        migrations.AlterField(
            model_name='clasificacioncausa',
            name='derecho',
            field=models.CharField(max_length=100, verbose_name='Derecho'),
        ),
    ]
