# Generated by Django 3.1.5 on 2021-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0003_auto_20210205_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacioncausa',
            name='categoria',
            field=models.PositiveIntegerField(choices=[(1, 'ACCESO A LOS SERVICIOS DE SALUD'), (2, 'ACCESO A LA INFORMACIÓN'), (3, 'ATENCIÓN Y RECUPERACIÓN DE LA SALUD'), (4, 'CONSENTIMIENTO INFORMADO'), (5, 'PROTECCIÓN DE DERECHOS'), (6, 'OTROS')], default=1, verbose_name='Derecho'),
        ),
    ]
