# Generated by Django 3.1.5 on 2021-02-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0004_clasificacioncausa_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificacioncausa',
            name='derecho',
        ),
    ]
