# Generated by Django 3.1.5 on 2021-02-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0005_remove_clasificacioncausa_derecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='clasificacion_reclamo_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_reclamo_1', to='reclamo.clasificacioncausa', verbose_name='Clasificación del reclamo 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='clasificacion_reclamo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_reclamo_2', to='reclamo.clasificacioncausa', verbose_name='Clasificación del reclamo 2'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='clasificacion_reclamo_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_reclamo_3', to='reclamo.clasificacioncausa', verbose_name='Clasificación del reclamo 3'),
        ),
    ]
