# Generated by Django 3.1.5 on 2021-02-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20210210_1123'),
        ('reclamo', '0006_auto_20210208_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.usuario', verbose_name='Período de declaración'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='resultado_reclamo',
            field=models.IntegerField(choices=[(0, 'PENDIENTE'), (1, 'FUNDADO'), (2, 'FUNDADO PARCIAL'), (3, 'INFUNDADO'), (4, 'IMPROCEDENTE'), (5, 'CONCLUIDO ANTICIPADAMENTE')], verbose_name='Resultado del Reclamo'),
        ),
    ]
