# Generated by Django 3.1.5 on 2021-02-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_entidad_ris'),
        ('reclamo', '0007_auto_20210210_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadreclamo',
            name='codigo_ugipress',
        ),
        migrations.RemoveField(
            model_name='entidadreclamo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='entidadreclamo',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.entidad', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='medio_presentacion',
            field=models.PositiveIntegerField(choices=[(1, 'VIRTUAL'), (2, 'FÍSICO')], verbose_name='Medio presentación'),
        ),
    ]
