# Generated by Django 3.1.5 on 2021-02-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0008_auto_20210210_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidadreclamo',
            old_name='apellido_materno_presente',
            new_name='apellido_materno_presenta',
        ),
    ]
