# Generated by Django 3.1.5 on 2021-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0009_auto_20210210_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='numero_documento_presenta',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número del documento de identidad de quien presenta el reclamo'),
        ),
    ]
