# Generated by Django 3.1.5 on 2021-02-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0010_auto_20210210_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='numero_documento_presenta',
            field=models.CharField(default=1, max_length=15, verbose_name='Número del documento de identidad de quien presenta el reclamo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='numero_documento_usuario',
            field=models.CharField(default=1, max_length=15, verbose_name='Número del documento de identidad del usuario afectado'),
            preserve_default=False,
        ),
    ]
