# Generated by Django 3.1.5 on 2021-02-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0011_auto_20210212_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadreclamo',
            name='codigo_administrador',
        ),
        migrations.RemoveField(
            model_name='entidadreclamo',
            name='tipo_administrador',
        ),
    ]
