# Generated by Django 3.1.5 on 2021-02-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0012_auto_20210222_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(default=1, max_length=15, verbose_name='Código Único de Registro del Reclamo asignado por el administrador'),
            preserve_default=False,
        ),
    ]
