# Generated by Django 3.1.5 on 2021-02-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_entidad_tipo'),
        ('reclamo', '0013_auto_20210222_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='periodo_declaracion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup.periodo'),
            preserve_default=False,
        ),
    ]
