# Generated by Django 3.1.5 on 2021-02-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_entidad_tipo'),
        ('reclamo', '0014_auto_20210222_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='detalle_reclamo',
            field=models.TextField(max_length=3000, verbose_name='Detalle del reclamo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='entidadreclamo',
            unique_together={('entidad', 'codigo_registro')},
        ),
    ]
