# Generated by Django 3.1.5 on 2021-02-22 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0015_auto_20210222_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='fecha_reclamo',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de presentación de Reclamo'),
            preserve_default=False,
        ),
    ]
