# Generated by Django 3.1.5 on 2021-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0016_auto_20210222_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='tipo_administrado_traslado',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'IPRESS'), (2, 'UGIPRESS'), (3, 'IAFAS')], null=True, verbose_name='Tipo de Administrado a la que se deriva o  traslada el reclamo'),
        ),
    ]
