# Generated by Django 3.1.5 on 2021-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0017_auto_20210222_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='etapa_reclamo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ADMISIÓN Y REGISTRO'), (2, 'EVALUACIÓN E INVESTIGACIÓN'), (3, 'RESULTADO Y NOTIFICACIÓN'), (4, 'ARCHIVO Y CUSTODIA DEL EXPEDIENTE')], null=True, verbose_name='Etapa del reclamo'),
        ),
        migrations.AlterField(
            model_name='medidaadoptada',
            name='procesos',
            field=models.PositiveIntegerField(choices=[(1, 'AFILIACIÓN'), (2, 'ACREDITACIÓN'), (3, 'PRESTACIÓN DE SERVICIOS SALUD'), (4, 'LIQUIDACIÓN, COBRO O PAGO A USUARIO POR LOS SERVICIOS'), (5, 'CONTRALLACIÓN DE SERVICIOS DE SALUD DE UNA IAFAS A UNA IPRESS PARA ATENCIÓN DE SUS ASEGURADOS)'), (6, 'OTRO PROCESO')], verbose_name='Proceso sobre el cual recae la Medida adoptada'),
        ),
    ]
