# Generated by Django 3.1.5 on 2021-02-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0018_auto_20210222_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='comunicacion_resultado_reclamo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'DOMICILIO CONSIGNADO EN EL LIBRO DE RECLAMACIONES EN SALUD'), (2, 'CORREO ELECTRÓNICO'), (3, 'OTRA DIRECCIÓN')], null=True, verbose_name='Comunicación de resultado del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='estado_reclamo',
            field=models.PositiveIntegerField(choices=[(1, 'RESUELTO'), (2, 'EN TRAMITE'), (3, 'TRASLADADO'), (4, 'ARCHIVADO POR DUPLICIDAD'), (5, 'ACUMULADO'), (6, 'CONCLUIDO (CUANDO EL RESULTADO ES COMUNICADO AL RECLAMANTE O TERCERO LEGITIMADO)')], verbose_name='Estado del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='motivo_conclusion_anticipada',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'DESISTIMIENTO POR ESCRITO'), (2, 'TRATO DIRECTO'), (3, 'CONCILIACIÓN'), (4, 'TRANSACCIÓN EXTRAJUDICIAL'), (5, 'LAUDO ARBITRAL')], null=True, verbose_name='Motivo de Conclusión anticipada'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='resultado_reclamo',
            field=models.IntegerField(blank=True, choices=[(0, 'PENDIENTE'), (1, 'FUNDADO'), (2, 'FUNDADO PARCIAL'), (3, 'INFUNDADO'), (4, 'IMPROCEDENTE'), (5, 'CONCLUIDO ANTICIPADAMENTE')], null=True, verbose_name='Resultado del Reclamo'),
        ),
    ]
