# Generated by Django 3.1.5 on 2021-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0019_auto_20210223_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='es_mismo_usuario_afectado',
            field=models.BooleanField(default=False, verbose_name='Es el mismo usuario afectado ?'),
        ),
    ]
