# Generated by Django 3.1.5 on 2021-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0020_entidadreclamo_es_mismo_usuario_afectado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadreclamo',
            name='periodo_declaracion',
        ),
        migrations.AddField(
            model_name='entidadreclamo',
            name='periodo',
            field=models.CharField(default='000000', max_length=6, verbose_name='Periodo'),
        ),
    ]
