# Generated by Django 3.1.5 on 2021-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0021_auto_20210326_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='estado_reclamo',
            field=models.PositiveIntegerField(choices=[(1, 'RESUELTO'), (2, 'EN TRAMITE'), (3, 'TRASLADADO'), (4, 'ARCHIVADO POR DUPLICIDAD'), (5, 'ACUMULADO'), (6, 'CONCLUIDO')], verbose_name='Estado del reclamo'),
        ),
    ]
