# Generated by Django 3.1.5 on 2021-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0022_auto_20210412_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_administrado',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código del administrado donde se presentó el reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_registro',
            field=models.CharField(max_length=15, verbose_name='Código Único de Registro del Reclamo asignado por el administrado'),
        ),
    ]
