# Generated by Django 3.1.5 on 2021-04-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0023_auto_20210412_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='detalle_reclamo',
            field=models.TextField(max_length=1500, verbose_name='Detalle del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='servicio_hecho_reclamo',
            field=models.CharField(choices=[('01', 'CONSULTA EXTERNA'), ('02', 'HOSPITALIZACION'), ('03', 'EMERGENCIA'), ('04', 'CENTRO QUIRDRGICO'), ('05', 'CENTRO OBSTÉTRICO'), ('06', 'UCI O UCIN'), ('07', 'FARMACIA'), ('08', 'SERVICIOS MÉDICOS DE APOYO'), ('09', 'ATENCIÉN A DOMICILIO CONSULTA AMBULATORIA'), ('10', 'ATENCIÉN A DOMICILIO URGENCIA A EMERGENCIA'), ('11', 'OFICINAS O AREAS ADMINISTRATIVAS DE IAFAS A 1 PRESS A UGIPRESS '), ('12', 'LNFRAESTRUCTURA'), ('13', 'REFERENCIA Y CONTRAREFERENCIA')], max_length=2, verbose_name='Servicio donde se efectuo el hecho que origino el reclamo'),
        ),
    ]
