# Generated by Django 3.1.5 on 2021-04-15 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0024_auto_20210415_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidaadoptada',
            name='fecha_culminacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de culminación provista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medidaadoptada',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio de implementación'),
            preserve_default=False,
        ),
    ]
