# Generated by Django 3.1.5 on 2021-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0025_auto_20210415_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='periodo',
            field=models.CharField(default='000000', max_length=6, verbose_name='Periodo de declaración'),
        ),
    ]
