# Generated by Django 3.1.5 on 2022-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0026_auto_20210503_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='medio_presentacion',
            field=models.PositiveIntegerField(choices=[(1, 'VIRTUAL'), (2, 'FÍSICO'), (3, 'TELEFÓNICO')], verbose_name='Medio presentación'),
        ),
    ]
