# Generated by Django 3.1.5 on 2022-03-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0027_auto_20220208_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='expediente',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Expediente'),
        ),
    ]
