# Generated by Django 3.1.5 on 2022-03-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20220208_1424'),
        ('reclamo', '0028_entidadreclamo_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='setup.entidad', verbose_name='Entidad'),
        ),
        migrations.AlterField(
            model_name='medidaadoptada',
            name='entidad_reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_adoptadas', to='reclamo.entidadreclamo'),
        ),
    ]
