# Generated by Django 3.1.5 on 2022-03-08 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20220208_1424'),
        ('reclamo', '0029_auto_20220304_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinReclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(choices=[(2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Año')),
                ('periodo', models.PositiveIntegerField(choices=[(1, 'ENERO'), (2, 'FEBRERO'), (3, 'MARZO'), (4, 'ABRIL'), (5, 'MAYO'), (6, 'JUNIO'), (7, 'JULIO'), (8, 'AGOSTO'), (9, 'SETIEMBRE'), (10, 'OCTUBRE'), (11, 'NOVIEMBRE'), (12, 'DICIEMBRE')], verbose_name='Periodo')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamo_created_by', to='setup.usuario')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.entidad')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reclamo_updated_by', to='setup.usuario')),
            ],
            options={
                'verbose_name': 'Sin reclamo',
                'verbose_name_plural': 'Sin reclamo',
                'unique_together': {('entidad', 'anio', 'periodo')},
            },
        ),
    ]
