# Generated by Django 3.1.5 on 2022-03-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20220208_1424'),
        ('reclamo', '0030_sinreclamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadreclamo',
            options={'ordering': ['fecha_reclamo'], 'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
        migrations.AlterField(
            model_name='sinreclamo',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sin_reclamos', to='setup.entidad'),
        ),
    ]
