# Generated by Django 3.1.5 on 2022-11-30 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0031_auto_20220309_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadreclamo',
            options={'ordering': ['-id'], 'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
    ]
