# Generated by Django 3.1.5 on 2022-12-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0032_auto_20221129_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='codigo_administrado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código del administrado donde se presentó el reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='competencia_reclamo',
            field=models.PositiveIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'COMPARTIDA'), (77, 'Elija la competencia para la atención del reclamo')], verbose_name='Competencia para la atencion del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='estado_reclamo',
            field=models.PositiveIntegerField(choices=[(1, 'RESUELTO'), (2, 'EN TRAMITE'), (3, 'TRASLADADO'), (4, 'ARCHIVADO POR DUPLICIDAD'), (5, 'ACUMULADO'), (6, 'CONCLUIDO'), (77, 'Elija de estado del reclamo')], verbose_name='Estado del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='etapa_reclamo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ADMISIÓN Y REGISTRO'), (2, 'EVALUACIÓN E INVESTIGACIÓN'), (3, 'RESULTADO Y NOTIFICACIÓN'), (4, 'ARCHIVO Y CUSTODIA DEL EXPEDIENTE'), (77, 'Eleija la etapa de reclamoo')], null=True, verbose_name='Etapa del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='servicio_hecho_reclamo',
            field=models.CharField(choices=[('01', 'CONSULTA EXTERNA'), ('02', 'HOSPITALIZACION'), ('03', 'EMERGENCIA'), ('04', 'CENTRO QUIRDRGICO'), ('05', 'CENTRO OBSTÉTRICO'), ('06', 'UCI O UCIN'), ('07', 'FARMACIA'), ('08', 'SERVICIOS MÉDICOS DE APOYO'), ('09', 'ATENCIÉN A DOMICILIO CONSULTA AMBULATORIA'), ('10', 'ATENCIÉN A DOMICILIO URGENCIA A EMERGENCIA'), ('11', 'OFICINAS O AREAS ADMINISTRATIVAS DE IAFAS A 1 PRESS A UGIPRESS '), ('12', 'LNFRAESTRUCTURA'), ('13', 'REFERENCIA Y CONTRAREFERENCIA'), ('77', 'Elija el servicio donde se originó el reclamo')], max_length=2, verbose_name='Servicio donde se efectuo el hecho que origino el reclamo'),
        ),
    ]
