# Generated by Django 5.0.7 on 2024-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0033_auto_20221205_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='comunicacion_resultado_reclamo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'DOMICILIO CONSIGNADO EN EL LIBRO DE RECLAMACIONES EN SALUD'), (2, 'CORREO ELECTRÓNICO'), (3, 'OTRA DIRECCIÓN PROPORCIONADA POR EL USUARIO O TERCERO LEGITIMADO A EFECTOS DE SER NOTIFICADO'), (4, 'NOTIFICACIÓN EXPRESADA POR EL USUARIO EN EL LIBRO DE RECLAMACIONES'), (5, 'AL TELÉFONO ACREDITADO POR EL USUARIO'), (6, 'NO SE LOGRA NOTIFICAR DEBIDO A IMPRECISIONES EN DIRECCIÓN-CORREO ATRIBUIBLES AL USUARIO')], null=True, verbose_name='Comunicación de resultado del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='estado_reclamo',
            field=models.PositiveIntegerField(choices=[(1, 'RESUELTO'), (2, 'EN TRAMITE'), (3, 'TRASLADADO'), (4, 'ARCHIVADO POR DUPLICIDAD'), (5, 'ACUMULADO'), (6, 'CONCLUIDO'), (77, 'Elija de estado del reclamo'), (0, 'REGISTRADO')], verbose_name='Estado del reclamo'),
        ),
        migrations.AlterField(
            model_name='sinreclamo',
            name='anio',
            field=models.PositiveIntegerField(choices=[(2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Año'),
        ),
    ]
