# Generated by Django 5.0.7 on 2024-08-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0034_alter_entidadreclamo_comunicacion_resultado_reclamo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadreclamo',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='entidadreclamo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='clasificacion_reclamo_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_reclamo_1', to='reclamo.clasificacioncausa', verbose_name='Clasificación del reclamo 1'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='competencia_reclamo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (3, 'COMPARTIDA'), (77, 'Elija la competencia para la atención del reclamo')], null=True, verbose_name='Competencia para la atencion del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='estado_reclamo',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'RESUELTO'), (2, 'EN TRAMITE'), (3, 'TRASLADADO'), (4, 'ARCHIVADO POR DUPLICIDAD'), (5, 'ACUMULADO'), (6, 'CONCLUIDO'), (77, 'Elija de estado del reclamo'), (0, 'REGISTRADO')], null=True, verbose_name='Estado del reclamo'),
        ),
        migrations.AlterField(
            model_name='entidadreclamo',
            name='servicio_hecho_reclamo',
            field=models.CharField(blank=True, choices=[('01', 'CONSULTA EXTERNA'), ('02', 'HOSPITALIZACION'), ('03', 'EMERGENCIA'), ('04', 'CENTRO QUIRDRGICO'), ('05', 'CENTRO OBSTÉTRICO'), ('06', 'UCI O UCIN'), ('07', 'FARMACIA'), ('08', 'SERVICIOS MÉDICOS DE APOYO'), ('09', 'ATENCIÉN A DOMICILIO CONSULTA AMBULATORIA'), ('10', 'ATENCIÉN A DOMICILIO URGENCIA A EMERGENCIA'), ('11', 'OFICINAS O AREAS ADMINISTRATIVAS DE IAFAS A 1 PRESS A UGIPRESS '), ('12', 'LNFRAESTRUCTURA'), ('13', 'REFERENCIA Y CONTRAREFERENCIA'), ('77', 'Elija el servicio donde se originó el reclamo')], max_length=2, null=True, verbose_name='Servicio donde se efectuo el hecho que origino el reclamo'),
        ),
        migrations.AlterModelTable(
            name='entidadreclamo',
            table='reclamo_entidadreclamo_prueba',
        ),
    ]
