# Generated by Django 5.1.1 on 2024-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0035_alter_entidadreclamo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadreclamo',
            name='tiene_medida',
            field=models.BooleanField(default=False),
        ),
    ]
