# Generated by Django 5.1.1 on 2024-10-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0036_entidadreclamo_tiene_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadreclamo',
            name='servicio_hecho_reclamo',
            field=models.CharField(blank=True, choices=[('01', 'CONSULTA EXTERNA'), ('02', 'HOSPITALIZACIÓN'), ('03', 'EMERGENCIA'), ('04', 'CENTRO QUIRÚRGICO'), ('05', 'CENTRO OBSTÉTRICO'), ('06', 'UCI O UCIN'), ('07', 'FARMACIA'), ('08', 'SERVICIOS MÉDICOS DE APOYO'), ('09', 'ATENCIÓN A DOMICILIO CONSULTA AMBULATORIA'), ('10', 'ATENCIÓN A DOMICILIO URGENCIA A EMERGENCIA'), ('11', 'OFICINAS O ÁREAS ADMINISTRATIVAS DE IAFAS A 1 PRESS A UGIPRESS '), ('12', 'INFRAESTRUCTURA'), ('13', 'REFERENCIA Y CONTRAREFERENCIA'), ('77', 'Elija el servicio donde se originó el reclamo')], max_length=2, null=True, verbose_name='Servicio donde se efectuo el hecho que origino el reclamo'),
        ),
    ]
