# Generated by Django 5.1.1 on 2024-10-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0037_alter_entidadreclamo_servicio_hecho_reclamo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entidadreclamo',
            table='reclamo_entidadreclamo',
        ),
    ]
