# Generated by Django 5.1.1 on 2024-11-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamo', '0038_alter_entidadreclamo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('status_code', models.IntegerField()),
                ('response_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='entidadreclamo',
            name='prioridad_clasificador_1',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Prioridad clasificador 1'),
        ),
        migrations.AddField(
            model_name='entidadreclamo',
            name='prioridad_clasificador_2',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Prioridad clasificador 2'),
        ),
        migrations.AddField(
            model_name='entidadreclamo',
            name='prioridad_clasificador_3',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Prioridad clasificador 3'),
        ),
        migrations.AlterField(
            model_name='sinreclamo',
            name='anio',
            field=models.PositiveIntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Año'),
        ),
    ]
